#!/usr/bin/env ruby

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH
Rails.application.require_environment!

Checkin.find(:all) do |t|
  puts "#{t.latitude}\t#{t.longitude}"
end

